resources:
- name: tools-image
  type: docker-image
  source:
    repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/cloud-platform/tools
    tag: latest
    aws_access_key_id: ((aws-live-1.access-key-id))
    aws_secret_access_key: ((aws-live-1.secret-access-key))
- name: cronjobber-image
  type: docker-image
  source:
    repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/cloud-platform/tzcronjobber
    tag: 0.2.0
    aws_access_key_id: ((aws-live-1.access-key-id))
    aws_secret_access_key: ((aws-live-1.secret-access-key))
jobs:
  - name: cronjobber
    plan:
      - get: tools-image
      - task: download
        image: tools-image
        config:
          platform: linux
          params:
            RELEASE: 0.2.0
          run:
            path: /bin/bash
            dir: files
            args:
              - -exc
              - |
                wget -q https://github.com/hiddeco/cronjobber/archive/${RELEASE}.tar.gz
                tar xzf ${RELEASE}.tar.gz --strip-components=1
          outputs:
            - name: files
      - put: cronjobber-image
        inputs: [files]
        params:
          build: files
          dockerfile: files/Dockerfile
          tag_as_latest: false
          cache: false
