#!/bin/sh

set -o pipefail
set -o errexit

usage() {
  printf "${0} <cluster-name>\n"
}

if [ $# != 1 ]; then
  usage
  exit 1
fi

cd resources

terraform init
terraform workspace new "${1}" || terraform workspace select "${1}"
terraform apply -auto-approve

_helm="helm --tiller-namespace concourse"

$_helm init --service-account tiller

if $_helm get concourse >/dev/null 2>&1; then
  $_helm upgrade \
    concourse \
    stable/concourse \
    --recreate-pods \
    -f ".helm-config/${1}/values.yaml"
else
  $_helm install \
    --namespace concourse \
    --name concourse \
    stable/concourse \
    -f ".helm-config/${1}/values.yaml"
fi
