slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
  channel: '#cloud-platform-chaos'
  silent: true
slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
  fallback: 'Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title: '$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title_link: 'https://concourse.apps.test-2.k8s.cloud-platform.dsd.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME'
  footer: concourse.apps.test-2.k8s.cloud-platform.dsd.io

resources:
- name: cloud-platform-environments-repo
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-environments.git
    branch: chaos-test-2
    git_crypt_key: ((cloud-platform-environments-git-crypt.key))
- name: tools-image
  type: docker-image
  source:
    repository: 754256621582.dkr.ecr.eu-west-1.amazonaws.com/cloud-platform-tools-image
    tag: latest
    aws_access_key_id: ((aws.access-key-id))
    aws_secret_access_key: ((aws.secret-access-key))
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/((slack-hook-id))
- name: every-15m
  type: time
  source:
    interval: 15m

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

jobs:
  - name: apply
    serial: true
    plan:
      - aggregate:
        - get: every-15m
          trigger: true
        - get: cloud-platform-environments-repo
          trigger: true
        - get: tools-image
      - task: apply-environments
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-environments-repo
          params:
            AWS_ACCESS_KEY_ID: ((aws.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws.secret-access-key))
            KUBECONFIG: /tmp/kubeconfig
            TF_PLUGIN_CACHE_DIR: /tmp/terraform-plugin-cache"
          run:
            path: /bin/sh
            dir: cloud-platform-environments-repo
            args:
              - -c
              - |
                mkdir -p "${TF_PLUGIN_CACHE_DIR}"
                aws s3 cp s3://cloud-platform-concourse-build-environments/kubeconfig /tmp/kubeconfig
                ./bin/apply
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
